name: savoir_plus
description: Plateforme Savoir+ MVP en Flutter Web avec Firebase et multilingue
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Si Hive encore utilisé
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.3

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.1
  firebase_storage: ^12.4.10
  url_launcher: ^6.1.10
  supabase_flutter: ^1.4.0
  flutter_signin_button: ^2.0.0

  # Jitsi Meet SDK
  jitsi_meet_flutter_sdk: ^11.0.0

  # UI et outils
  multi_select_flutter: ^4.1.3
  file_picker: ^10.3.1
  open_filex: ^4.4.0
  open_file: ^3.5.10

  # Audio / permissions
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.0

  # Appels vidéo
  flutter_webrtc: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/app_icon.png
