// lib/constants.dart

/// 🌍 Liste de tous les pays du monde (ordre alphabétique simplifié)
const List<String> countriesList = [
  'Afghanistan',
  'Afrique du Sud',
  'Albanie',
  'Algérie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Antigua-et-Barbuda',
  'Arabie Saoudite',
  'Argentine',
  'Arménie',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bangladesh',
  'Barbade',
  'Belgique',
  'Bélarus',
  'Bermudes',
  'Bhoutan',
  'Bolivie',
  'Bosnie-Herzégovine',
  'Botswana',
  'Brésil',
  'Brunei',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Cap-Vert',
  'Chili',
  'Chine',
  'Colombie',
  'Congo',
  'Corée du Sud',
  'Costa Rica',
  'Côte d\'Ivoire',
  'Croatie',
  'Cuba',
  'Danemark',
  'Djibouti',
  'Dominique',
  'Égypte',
  'Émirats arabes unis',
  'Équateur',
  'Érythrée',
  'Espagne',
  'Estonie',
  'Éthiopie',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Géorgie',
  'Ghana',
  'Grèce',
  'Grenade',
  'Guatemala',
  'Guinée',
  'Guinée-Bissau',
  'Guyana',
  'Haïti',
  'Honduras',
  'Hongrie',
  'Îles Marshall',
  'Inde',
  'Indonésie',
  'Irak',
  'Iran',
  'Irlande',
  'Islande',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizistan',
  'Kiribati',
  'Kosovo',
  'Koweït',
  'Laos',
  'Lettonie',
  'Liban',
  'Libéria',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macédoine du Nord',
  'Madagascar',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Maroc',
  'Maurice',
  'Mauritanie',
  'Mexique',
  'Micronésie',
  'Moldavie',
  'Monaco',
  'Mongolie',
  'Monténégro',
  'Mozambique',
  'Namibie',
  'Nauru',
  'Népal',
  'Nicaragua',
  'Niger',
  'Nigéria',
  'Norvège',
  'Nouvelle-Zélande',
  'Oman',
  'Ouganda',
  'Ouzbékistan',
  'Pakistan',
  'Palaos',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pays-Bas',
  'Pérou',
  'Philippines',
  'Pologne',
  'Portugal',
  'Qatar',
  'République centrafricaine',
  'République tchèque',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Rwanda',
  'Saint-Christophe-et-Niévès',
  'Saint-Marin',
  'Saint-Vincent-et-les-Grenadines',
  'Sainte-Lucie',
  'Salvador',
  'Samoa',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Slovaquie',
  'Slovénie',
  'Somalie',
  'Soudan',
  'Sri Lanka',
  'Suède',
  'Suisse',
  'Suriname',
  'Syrie',
  'Tadjikistan',
  'Tanzanie',
  'Tchad',
  'Thaïlande',
  'Timor oriental',
  'Togo',
  'Tonga',
  'Trinité-et-Tobago',
  'Tunisie',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Viêt Nam',
  'Yémen',
  'Zambie',
  'Zimbabwe',
];

/// 🗣️ 50 langues les plus parlées dans le monde (ordre alphabétique)
const List<String> languagesList = [
  'Afrikaans',
  'Arabe',
  'Bengali',
  'Chinois',
  'Espagnol',
  'Français',
  'Géorgien',
  'Gujarati',
  'Haoussa',
  'Hébreu',
  'Hindi',
  'Hmong',
  'Indonésien',
  'Italien',
  'Japonais',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Kinyarwanda',
  'Kiswahili',
  'Konkani',
  'Kurde',
  'Laotien',
  'Lingala',
  'Malais',
  'Mandarin',
  'Marathi',
  'Néerlandais',
  'Népalais',
  'Odia',
  'Oromo',
  'Pashto',
  'Persan',
  'Polonais',
  'Portugais',
  'Roumain',
  'Russe',
  'Sérère',
  'Somali',
  'Sotho',
  'Suédois',
  'Tadjik',
  'Tamoul',
  'Tchèque',
  'Telugu',
  'Thai',
  'Turc',
  'Ukrainien',
  'Vietnamien',
  'Xhosa',
  'Yoruba',
  'Zoulou',
];

/// 📂 Catégories principales
const List<String> categoriesList = [
  'Toutes',
  'Informatique',
  'Cuisine',
  'Langues',
  'Musique',
  'Jardinage',
  'Sport',
  'Art',
  'Autre',
];

/// ⏳ Disponibilités
const List<String> availabilitiesList = [
  'Temps plein',
  'Temps partiel',
  'Week-ends',
  'Soirées',
  'Flexible',
];

/// 🛠️ Compétences générales
const List<String> skillsList = [
  'Programmation',
  'Cuisine',
  'Langues',
  'Musique',
  'Jardinage',
  'Sport',
  'Design',
  'Marketing',
  'Photographie',
];

/// 📚 Savoirs détaillés par catégorie
const Map<String, List<String>> knowledgeByCategory = {
  'Informatique': [
    'Programmation en Python',
    'Développement Web (HTML, CSS, JS)',
    'Flutter & Applications mobiles',
    'Bases de données (SQL, NoSQL)',
    'Cybersécurité',
    'Intelligence artificielle',
    'Réseaux informatiques',
    'Arduino & IoT',
  ],
  'Cuisine': [
    'Pâtisserie française',
    'Cuisine africaine',
    'Cuisine italienne (pâtes, pizza)',
    'Cuisine asiatique (sushis, nouilles)',
    'Cuisine végétarienne',
    'Techniques de grillade',
  ],
  'Langues': [
    'Français - Grammaire et expression',
    'Anglais - Conversation',
    'Espagnol - Débutant',
    'Allemand - Vocabulaire de base',
    'Arabe - Lecture et écriture',
    'Chinois - Introduction au mandarin',
  ],
  'Musique': [
    'Guitare (classique, acoustique)',
    'Piano - Bases et intermédiaire',
    'Chant et techniques vocales',
    'Batterie - Rythmes de base',
    'Violoncelle / Instruments à cordes',
    'Composition musicale',
  ],
  'Jardinage': [
    'Techniques de plantation',
    'Entretien potager',
    'Plantes médicinales',
    'Arrosage automatique',
    'Permaculture',
    'Entretien de pelouse',
  ],
  'Sport': [
    'Football - Techniques de jeu',
    'Basketball - Dribble et tir',
    'Natation - Bases et perfectionnement',
    'Athlétisme - Course de fond',
    'Fitness et musculation',
    'Yoga et méditation',
  ],
  'Art': [
    'Peinture (huile, acrylique, aquarelle)',
    'Dessin au crayon',
    'Sculpture',
    'Photographie artistique',
    'Montage vidéo',
    'Calligraphie',
  ],
  'Autre': [
    'Développement personnel',
    'Gestion du temps',
    'Prise de parole en public',
    'Entrepreneuriat',
    'Finance personnelle',
    'Éducation des enfants',
  ],
};
