// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb8RDeYJQwgELhuUXZ_MIR0CjSwotDYJk',
    appId: '1:779528846868:web:72fcb45dbcca50bf66f101',
    messagingSenderId: '779528846868',
    projectId: 'savoirplustests',
    authDomain: 'savoirplustests.firebaseapp.com',
    storageBucket: 'savoirplustests.appspot.com', // ✅ corrigé ici
    measurementId: 'G-5FDJH5M72T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVQMM843vIKfvBdvVWpE_w1grghe1WFQ',
    appId: '1:779528846868:android:9204f323dad6cc6866f101',
    messagingSenderId: '779528846868',
    projectId: 'savoirplustests',
    storageBucket: 'savoirplustests.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLVQMM843vIKfvBdvVWpE_w1grghe1WFQ',
    appId: '1:779528846868:ios:dummy-id',
    messagingSenderId: '779528846868',
    projectId: 'savoirplustests',
    storageBucket: 'savoirplustests.appspot.com',
    iosBundleId: 'com.example.savoirPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLVQMM843vIKfvBdvVWpE_w1grghe1WFQ',
    appId: '1:779528846868:ios:dummy-id',
    messagingSenderId: '779528846868',
    projectId: 'savoirplustests',
    storageBucket: 'savoirplustests.appspot.com',
    iosBundleId: 'com.example.savoirPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb8RDeYJQwgELhuUXZ_MIR0CjSwotDYJk',
    appId: '1:779528846868:web:7c48eddaf162d1c066f101',
    messagingSenderId: '779528846868',
    projectId: 'savoirplustests',
    authDomain: 'savoirplustests.firebaseapp.com',
    storageBucket: 'savoirplustests.appspot.com',
    measurementId: 'G-RX3LLNDZBQ',
  );
}